name=input("who are u")
city=input('where do you live')
age=input('how old you?')
hobby=input('what is your hobby?')
movie=input('what is favorite movie?')
food=input('whatis your favorite food?')

print("     YOUR DETAIL FILLED BY YOU      ")
print("name:",name)
print("city:",city)
print("age:",age)
print("hobby:",hobby)
print("movie:",movie)
print("food:",food)
print("    the end    ")